# Laboratory Activity 2

###### _Python — CCQUAMET_

In [4]:
# 1. Import the same data
import pandas as pd

df = pd.read_excel("Module2_Excel_LabAct 1.xlsx", skiprows=2) # Skip title

# 2. Clean the .csv file
df.drop_duplicates()

# 3. Show the first 5 rows
df.head()

,Student ID,Gender,Race/Ethnicity,Parental Education,Lunch Type,Test Prep Course,Math Score,Reading Score,Writing Score
0,S001,female,group B,bachelor's degree,standard,none,72,72,74
1,S002,female,group C,some college,standard,completed,69,90,88
2,S003,female,group B,master's degree,standard,none,90,95,93
3,S004,male,group A,associate's degree,free/reduced,none,47,57,44
4,S005,male,group C,some college,standard,none,76,78,75

In [5]:
# 4. Show datatypes of each column
print(df.dtypes)

Student ID              str
Gender                  str
Race/Ethnicity          str
Parental Education      str
Lunch Type              str
Test Prep Course        str
Math Score            int64
Reading Score         int64
Writing Score         int64
dtype: object

In [6]:
# 5. Summarize the data and round it into two decimal places
df.describe().round(2)

       Math Score  Reading Score  Writing Score
count       30.00          30.00          30.00
mean        62.00          67.43          64.47
std         16.84          16.28          16.65
min         18.00          32.00          28.00
25%         50.75          55.50          52.75
50%         64.50          68.00          64.00
75%         71.75          80.25          74.75
max         90.00          95.00          93.00