# **Python Sample Dataset Manipulation**
The _sample_data.csv_ is manipulated using Python through the _pandas_ library. With this library, the csv can be cleaned, sorted, and manipulated with other various functions.

The script shows the dataset **before** manipulation.

In [15]:
import pandas as pd
df = pd.read_csv("sample_data.csv")
print(df.shape)
df.head()

(10, 4)

     Name  Gender Section  Score
0     Ana  Female       A   85.0
1     Ben    Male       A  150.0
2     Jer    Male       B    NaN
3     Gab    Male       B   78.0
4  Sheesh  Female       A   92.0

The script below shows the dataset **after** manipulation.

In [16]:
# Remove score > 100 (impossible)
df = df[df['Score'] <= 100]

# Remove rows with missing score
df = df.dropna(subset=['Score'])

# Remove duplicate rows
df = df.drop_duplicates()
print(f'Clean rows: {len(df)}')
df.head()

Clean rows: 7

     Name  Gender Section  Score
0     Ana  Female       A   85.0
3     Gab    Male       B   78.0
4  Sheesh  Female       A   92.0
5     Ako  Female       B   66.0
7   Juana  Female       B   71.0

### Organization of Data
The script below shows how the dataset can be reorganized through various functions.

In [17]:
# Sort by score (high to low)
df_organized = df.sort_values('Score', ascending=False)

# Filter by score (Section A only)
df_organized = df_organized[df_organized['Section'] == 'A']

# Rename a column
df_organized = df_organized.rename(columns={'Score' : 'QuizScore'})

# Summary of statistics
df_organized.head()

     Name  Gender Section  QuizScore
4  Sheesh  Female       A       92.0
8    Ivan    Male       A       88.0
0     Ana  Female       A       85.0
9   Julia  Female       A       74.0

In [20]:
# Get the mean value of specific column
print("Mean of Quiz Score:", df_organized['QuizScore'].mean())

# Get the frequency of values in specified column
print(df_organized['Section'].value_counts())

# Show data types of each column
print(df_organized.dtypes)

df_organized.describe().round(2)

# For better clarity and specific column target
# df_organized['QuizScore'].describe()

Mean of Quiz Score: 84.75
Section
A    4
Name: count, dtype: int64
Name             str
Gender           str
Section          str
QuizScore    float64
dtype: object

       QuizScore
count       4.00
mean       84.75
std         7.72
min        74.00
25%        82.25
50%        86.50
75%        89.00
max        92.00