# **Python Dataset Manipulation**
The _sample_data.csv_ is manipulated using Python through the _pandas_ library. With this library, the csv can be cleaned, sorted, and manipulated with other various functions.

The script shows the dataset **before** manipulation.

In [3]:
import pandas as pd

df = pd.read_csv("sample_data.csv")

In [4]:
# Get dataset table shape
print(df.shape)

(10, 5)

In [5]:
# Display first 5 row of dataset
df.head()

   ##    Name  Gender Section  Score
0   1     Ana  Female       A   85.0
1   2     Ben    Male       A  150.0
2   3     Jer    Male       B    NaN
3   4     Gab    Male       B   78.0
4   5  Sheesh  Female       A   92.0

The script below shows the dataset **after** manipulation.

In [6]:
# Remove score > 100 (impossible)
df = df[df['Score'] <= 100]

# Remove rows with missing score
df = df.dropna(subset=['Score'])

# Remove duplicate rows
df = df.drop_duplicates()
print(f'Clean rows: {len(df)}')

Clean rows: 8

In [7]:
# Show clean dataset
df.head()

   ##    Name  Gender Section  Score
0   1     Ana  Female       A   85.0
3   4     Gab    Male       B   78.0
4   5  Sheesh  Female       A   92.0
5   6     Ako  Female       B   66.0
6   7     Ana  Female       A   85.0

### Organization of Data
The script below shows how the dataset can be reorganized through various functions.

In [8]:
# Sort by score (high to low)
df_organized = df.sort_values('Score', ascending=False)

# Filter by score (Section A only)
df_organized = df_organized[df_organized['Section'] == 'A']

# Rename a column
df_organized = df_organized.rename(columns={'Score' : 'QuizScore'})

# Summary of statistics
df_organized.head()

   ##    Name  Gender Section  QuizScore
4   5  Sheesh  Female       A       92.0
8   9    Ivan    Male       A       88.0
6   7     Ana  Female       A       85.0
0   1     Ana  Female       A       85.0
9  10   Julia  Female       A       74.0

In [9]:
# Get the mean value of specific column
print("Mean of Quiz Score:", df_organized['QuizScore'].mean())

Mean of Quiz Score: 84.8

In [10]:
# Get the frequency of values in specified column
print(df_organized['Section'].value_counts())

Section
A    5
Name: count, dtype: int64

In [11]:
# Show data types of each column
print(df_organized.dtypes)

##             int64
Name             str
Gender           str
Section          str
QuizScore    float64
dtype: object

In [12]:
# Round off data description
df_organized.describe().round(2)

          ##  QuizScore
count   5.00       5.00
mean    6.40      84.80
std     3.58       6.69
min     1.00      74.00
25%     5.00      85.00
50%     7.00      85.00
75%     9.00      88.00
max    10.00      92.00

In [13]:
# For better clarity and specific column target
df_organized['QuizScore'].describe()

count     5.000000
mean     84.800000
std       6.685806
min      74.000000
25%      85.000000
50%      85.000000
75%      88.000000
max      92.000000
Name: QuizScore, dtype: float64